#!/usr/bin/env bash
set -e

#MISE description="Starts aider to generate, or update, an actual migration yaml."
#USAGE flag "-f --force" help="Set this to ignore an empty template_migrations directory"
#USAGE arg "<migration_id>" help="The ID of the migration to guess the mapping for"

source "$MISE_TASK_DIR/../.includes/helpers.sh"

cd "$MISE_ORIGINAL_CWD"

if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  cd "$(git rev-parse --show-toplevel)"
fi

FORCE="${usage_force:-false}"
MIGRATION_ID="$usage_migration_id"

if [ ! -d ".migraine" ] ; then
  echo "Migraine directory .migraine does not exist or is not a directory. Have you run migraine:inventory?" >&2
  exit 1
fi

if [ ! -d ".migraine/prompts" ] || [ ! -r ".migraine/prompts/$MIGRATION_ID.md" ] ; then
  echo "Could not find .migraine/prompts/$MIGRATION_ID.md. Have you run migraine:make-prompt?" >&2
  exit 1
fi

if [ ! -d ".migraine/templates" ]; then
  mkdir ".migraine/templates"
fi

if [ ! -d ".migraine/templates/migrations" ]; then
  mkdir ".migraine/templates/migrations"
fi

if [ ! "$FORCE" == "true" ] && [ -z "$(find ".migraine/templates/migrations" -maxdepth 1 -name "*.yml" -type f -print -quit)" ]; then
  echo "" >&2
  echo "  [WARNING] There are no yml files in ".migraine/templates/migrations". You will see greatly improved" >&2
  echo "  results if you copy some example migrations into this folder. Why not copy some from Drupal 10"  >&2
  echo "  core locations such as:" >&2
  echo "    - core/modules/node/migrations/" >&2
  echo "    - core/modules/user/migrations/" >&2
  echo "" >&2
  echo "  To disregard this error and proceed anyway, pass the --force option to this command." >&2
  echo "" >&2
  exit 1
fi

run aider \
  --map-tokens=0 \
  --read=".migraine/prompts/$MIGRATION_ID.md" \
  --read=".migraine/templates/migrations" \
  --message="Read .migraine/prompts/$MIGRATION_ID.md and follow all instructions."
