#!/usr/bin/env bash
set -e

#MISE description="Generate migrations list by asking AI to guess."
#MISE alias="gm"
#USAGE flag "-m --model <model>" help="The LLM model to use" default="o1"
#USAGE flag "-i --improve" help="Feed the existing migrations.json to the LLM to improve"

source "$MISE_TASK_DIR/../.includes/helpers.sh"

cd "$MISE_ORIGINAL_CWD"

if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  cd "$(git rev-parse --show-toplevel)"
fi

MODEL="${usage_model:-o1}"
IMPROVE="$usage_improve"

if ! command -v llm 2>&1 >/dev/null
then
    echo "Please install llm to access migraine:llm:* tasks:" >&2
    echo "" >&2
    echo "    https://llm.datasette.io/" >&2
    echo "" >&2
    exit 1
fi

if [ ! -d ".migraine" ] || [ ! -r ".migraine/migraine.yml" ] ; then
  echo "Could not read .migraine/migraine.yml config. Have you run migraine:register?" >&2
  exit 1
fi

if [ ! -r ".migraine/inventory/source/types.json" ] ; then
  echo "Could not find .migraine/inventory/source/types.json. Have you run migraine:inventory source?" >&2
  exit 1
fi

if [ ! -r ".migraine/inventory/dest/types.json" ] ; then
  echo "Could not find .migraine/inventory/dest/types.json. Have you run migraine:inventory dest?" >&2
  exit 1
fi

SOURCE_VERSION=$(php "$MISE_TASK_DIR/../.includes/get-config.php" sites source drupalVersion 2>/dev/null)
DEST_VERSION=$(php "$MISE_TASK_DIR/../.includes/get-config.php" sites dest drupalVersion 2>/dev/null)

if [ -z "$SOURCE_VERSION" ] || [ -z "$DEST_VERSION" ]; then
  echo "Failed to parse .migraine/migraine.yml. Fix syntax issues." >&2
  exit 1
fi

if [ "$IMPROVE" == "true" ] && [ ! -r ".migraine/migrations.json" ]; then
  echo "--improve was passed, but cannot read .migraine/migrations.json"
  exit 1
fi

PROMPT=$(
cat <<- END_HEREDOC
You are an expert Drupal developer assisting with the planning and execution of a Drupal $SOURCE_VERSION to Drupal $DEST_VERSION migration.
Given the following list of entity types/bundles in the source $SOURCE_VERSION and destination $DEST_VERSION sites, please
suggest what migrations are needed.

SOURCE TYPES/BUNDLES

$(cat ".migraine/inventory/source/types.json")

DESTINATION TYPES/BUNDLES

$(cat ".migraine/inventory/dest/types.json")

END_HEREDOC
)

if [ "$IMPROVE" == "true" ]; then

  echo "Asking LLM to improve existing .migraine/migrations.json" >&2

  PROMPT=$(
  cat <<- END_HEREDOC
$PROMPT

IMPROVE PREVIOUS VERSION

The following JSON is an earlier listing of migrations, with guessed values. Keep the existing IDs, but examine the source/destinatino
data and improve the values where they seem wrong.

$(cat ".migraine/migrations.json")

END_HEREDOC
)
fi

PROMPT=$(
cat <<- END_HEREDOC
$PROMPT

OUTPUT FORMAT

You MUST output only a valid JSON string containing a single plain object where each value is a 4-tuple of
[SourceEntityType,SourceBundle,DestEntityType,DestBundle] and the key is a suitably chosen short unique machine ID for
that migration. For example:

{
  "node_article": ["node","article","node","article"],
  "media_image": ["file","file","media","image"]
  "media_video": ["file","file","media","video"]
  "paragraph_foo_from_field_foo": ["field_collection","field_foo","paragraph_item","foo"]
}

END_HEREDOC
)

echo "==> Asking LLM to generate migrations ==>" >&2
echo 'echo "$PROMPT" | llm prompt --model "'"$MODEL"'" --extract > '".migraine/migrations.json" >&2
echo "$PROMPT" | llm prompt --model "$MODEL" --extract > ".migraine/migrations.json"
