#!/usr/bin/env php
<?php
//MISE description="Register a Drupal site as source or dest."
//MISE alias="p"
//USAGE arg "<targetName>" help="'source' or 'dest'"
//USAGE arg "<dir>" help="Path to the local Drupal root"
//USAGE flag "--drush" default="" help="Set the command that invokes drush from the drupal root. Defaults to ddev drush."
//USAGE flag "-D --delete" help="Pass to unregister the site instead of register."
//USAGE flag "-n --no-inventory" help="Pass to skip taking inventory."

namespace Migraine;

use Symfony\Component\Filesystem\Path;

$projectRoot = getenv('MISE_ORIGINAL_CWD');
$taskDir = getenv('MISE_TASK_DIR');
$targetName = $argv[1];
$drupalRootPath = $argv[2];
$drushCmd = getenv('usage_drush');
$delete = getenv('usage_delete') === 'true';
$noInventory = getenv('usage_no-inventory') === 'true';

require_once "$taskDir/.includes/vendor/autoload.php";

$config = Config::forDirectory($projectRoot);

$resolver = _make_path_resolver($projectRoot);

$targetName = match($targetName) {
    's', 'source' => 'source',
    'd', 'dest', 'destination' => 'dest',
    default => $targetName,
};

$sites = $config->get('sites', []);

if ($delete) {
    if (!isset($sites[$targetName])) {
        _error('Could not find registered site named "%s".', $targetName);
        exit(1);
    }
    unset($sites[$targetName]);
    $config->set('sites', $sites);
    _rmrf($config->getPath(['inventory', $targetName]));

    _log('Unregistered site named "%s".', $targetName);
    exit;
}

$drupalRootPath = $resolver($drupalRootPath, 'Could not find a directory at %s.');

try {
  $root = new DrupalRoot($drupalRootPath);
}
catch (\Exception $e) {
  _error($e->getMessage());
  exit(1);
}

if (isset($sites[$targetName]['drush']) && empty($drushCmd)) {
    $drushCmd = $sites[$targetName]['drush'];
}

$drushStatus = _execGetJson($root->getDrupalRoot(), sprintf('%s status --format=json', $drushCmd));

if (!is_array($drushStatus)) {
    _error('Error executing % status in %s: %s', $drushCmd, $root->getDrupalRoot(), $drushStatus);
    _error('To change the command used to invoke drush, pass via --drush="<command>".');
    exit(1);
}

$sites[$targetName]['drupalVersion'] = $drushStatus['drupal-version'] ?? $root->getMajorDrupalVersion();
$sites[$targetName]['path'] = Path::makeRelative($root->getDrupalRoot(), getcwd());
$sites[$targetName]['drush'] = $drushCmd;
$sites[$targetName]['inventoried'] = false;
krsort($sites);

_log(
    'Registered %s Drupal %d root at %s.',
    $targetName, $root->getMajorDrupalVersion(), $root->getDrupalRoot(),
);

$config->set('sites', $sites);

if ($noInventory) {
  exit;
}

_log('Taking initial inventory..');

_exec($projectRoot, sprintf(
  '%s %s --drush="%s"',
    realpath(Path::join($taskDir, 'inventory')),
    $targetName,
    $drushCmd,
));
