#!/usr/bin/env php
<?php
//MISE description="Show status of registered sites."
//MISE alias="s"

namespace Migraine;

$projectRoot = getenv('MISE_ORIGINAL_CWD');
$taskDir = getenv('MISE_TASK_DIR');

require_once "$taskDir/.includes/vendor/autoload.php";

$config = Config::forDirectory($projectRoot);

$rows = [];
$sites = $config->get('sites', []);
foreach (array_keys($sites) as $name) {
    $status = 'OK';

    $drushCmd = $sites['drush'] ?? 'ddev drush';

    try {
        $root = new DrupalRoot($sites[$name]['path']);

        $drushStatus = _execGetJson($root->getDrupalRoot(), sprintf('%s status --format=json', $drushCmd));

        if (!is_array($drushStatus)) {
            $status = 'DRUSH ERROR';
        }
        else {
            if (isset($drushStatus['drupal-version'])) {
                $sites[$name]['drupalVersion'] = $drushStatus['drupal-version'];
            }
            if (!isset($drushStatus['db-status']) || $drushStatus['db-status'] !== 'Connected') {
                $status = 'DATABASE ERROR';
            }
        }
    }
    catch (\Exception) {
        $status = 'MISSING';
    }

    $lastInventoried = !empty($sites[$name]['inventoried'])
        ? _format_time_diff_since($sites[$name]['inventoried']) . ' ago'
        : 'n/a';

    $rows[] = [
        $name,
        realpath($sites[$name]['path']) ?: $sites[$name]['path'],
        $sites[$name]['drupalVersion'],
        $status,
        $lastInventoried,
    ];
}

$config->set('sites', $sites);

_log('');
_log((new TextTable(
    ['SITE', 'PATH', 'DRUPAL VERSION', 'STATUS', 'LAST INVENTORIED'],
    $rows,
))->render());
